---
- name: Identify VMFS datastores to ESXi
  hosts: localhost
  become: yes
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Get Canonical name of particular target on particular ESXi host system
      vmware_target_canonical_info:
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        validate_certs: 'false'
        esxi_hostname: [bm-esxi-ocp]