---
- name: Add Port Group to ESXi Host
  hosts: localhost
  become: yes
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Create Port Group
      vmware_portgroup:
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        hosts: [bm-esxi-ocp]
        validate_certs: false
        vswitch: vSwitch0
        portgroup: VM Network
        vlan_id: 1
        state: present



