- name: ESXi Host
  hosts: localhost
  become: yes
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: start vm
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: bootstrap
        state: powered-off
      

    - name: start vm
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-cp-1
        state: powered-off
        

    - name: start vm
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-cp-2
        state: powered-off
        

    - name: start vm
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-cp-3
        state: powered-off


    - name: start vm
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-w-1
        state: powered-off
        

    - name: start vm
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-w-2
        state: powered-off
       

    - name: start vm
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-w-3
        state: powered-off
        