---
- name: ESXi Host
  hosts: localhost
  become: yes
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Delete a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: bootstrap
        state: absent
        force: true
        guest_id: coreos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be removeed
        esxi_hostname: bm-esxi-ocp
        disk:
        - size_gb: 120
          type: thick
          datastore: VMs
        hardware:
          memory_mb: 16384
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: 02:50:68:00:00:10
          device_type: vmxnet3
      register: remove_bootstrap

    - name: Delete a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-cp-1
        state: absent
        force: true
        guest_id: coreos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be removeed
        esxi_hostname: bm-esxi-ocp
        disk:
        - size_gb: 120
          type: thick
          datastore: VMs
        hardware:
          memory_mb: 16384
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: 02:50:68:00:00:20
          device_type: vmxnet3
      register: remove_ocpcp1  
    
    - name: Delete a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-cp-2
        state: absent
        force: true
        guest_id: coreos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be removeed
        esxi_hostname: bm-esxi-ocp
        disk:
        - size_gb: 120
          type: thick
          datastore: VMs
        hardware:
          memory_mb: 16384
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: 02:50:68:00:00:30
          device_type: vmxnet3
      register: remove_ocpcp2

    - name: Delete a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-cp-3
        state: absent
        force: true
        guest_id: coreos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be removeed
        esxi_hostname: bm-esxi-ocp
        disk:
        - size_gb: 120
          type: thick
          datastore: VMs
        hardware:
          memory_mb: 16384
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: 02:50:68:00:10:10
          device_type: vmxnet3
      register: remove_ocpcp3

    - name: Delete a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-w-1
        state: absent
        force: true
        guest_id: coreos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be removeed
        esxi_hostname: bm-esxi-ocp
        disk:
        - size_gb: 120
          type: thick
          datastore: VMs
        hardware:
          memory_mb: 16384
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: 02:50:68:00:20:10
          device_type: vmxnet3
      register: remove_ocpw1 

    - name: Delete a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-w-2
        state: absent
        force: true
        guest_id: coreos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be removeed
        esxi_hostname: bm-esxi-ocp
        disk:
        - size_gb: 120
          type: thick
          datastore: VMs
        hardware:
          memory_mb: 16384
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: 02:50:68:00:30:10
          device_type: vmxnet3
      register: remove_ocpw2

    - name: Delete a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        validate_certs: false 
        hostname: "161.156.81.115"
        username: "root"
        password: "d8HUT0R$tNxNgH2A7ky5"
        folder: /ha-datacenter/vm
        name: ocp-w-3
        state: absent
        force: true
        guest_id: coreos64Guest
        # This is hostname of particular ESXi server on which user wants VM to be removeed
        esxi_hostname: bm-esxi-ocp
        disk:
        - size_gb: 120
          type: thick
          datastore: VMs
        hardware:
          memory_mb: 16384
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: 02:50:68:00:40:10
          device_type: vmxnet3
      register: remove_ocpw3